---
- name: Adding GnuPG key for elasticsearch repos...
  apt_key: id=D88E42B4 url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Enabling Elasticsearch 1.0.x repository...
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/1.0/debian stable main' state=present
  when: use_elasticsearch

- name: Enabling Logstash 1.4.x repository...
  apt_repository: repo='deb http://packages.elasticsearch.org/logstash/1.4/debian stable main' state=present
  when: use_logstash
